# Server configuration
server:
    port: 9090
    undertow:
        threads:
            io: 4
            worker: 32

# Database configuration
database:
    driver: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_MYSQL_URL:jdbc:mysql://codeflix-catalog-backend-db:3306/codeflix_adm_videos}
    user: ${DATABASE_MYSQL_USERNAME:root}
    password: ${DATABASE_MYSQL_PASSWORD:root}
