# Server configuration
server:
    port: 9090
    undertow:
        threads:
            io: 4
            worker: 32

# Database configuration
mysql:
    url: jdbc:mysql://codeflix-catalog-backend-db
    port: 3306
    schema: codeflix
    username: root
    password: root
