# Server configuration
server:
    port: 8080
    undertow:
        threads:
            io: 2
            worker: 16

# Database configuration
database:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://codeflix-catalog-backend-db:3306/codeflix_adm_videos
    user: root
    password: root
