# Server configuration
server:
    port: 9090
    undertow:
        threads:
            io: 4
            worker: 32

# Database configuration
database:
    driver: org.h2.Driver
    #    url: jdbc:h2:mem:codeflix_adm_videos_test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:codeflix-${random.uuid};MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    user: sa
    password: sa


spring:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        # Defers datasource initialization if needed. This setting can prevent initialization issues
        # when the datasource is not immediately available.
        defer-datasource-initialization: false
        hibernate:
            ddl-auto: none

    h2:
        console:
            enabled: true
            path: /h2
