databaseChangeLog:
    -   changeSet:
            id: 0001-initial-categories
            author: Josenaldo de Oliveira Matos Filho
            preConditions:
                onFail: MARK_RAN
                not:
                    tableExists:
                        tableName: categories
            changes:
                -   createTable:
                        tableName: categories
                        columns:
                            -   column:
                                    name: id
                                    type: VARCHAR(26)
                                    constraints:
                                        primaryKey: true
                                        nullable: false
                            -   column:
                                    name: created_at
                                    type: DATETIME(6)
                                    constraints:
                                        nullable: false
                            -   column:
                                    name: updated_at
                                    type: DATETIME(6)
                                    constraints:
                                        nullable: false
                            -   column:
                                    name: deleted_at
                                    type: DATETIME(6)
                            -   column:
                                    name: name
                                    type: VARCHAR(255)
                                    constraints:
                                        nullable: false
                            -   column:
                                    name: description
                                    type: VARCHAR(4000)
                            -   column:
                                    name: active
                                    type: BOOLEAN
                                    defaultValueBoolean: true
                                    constraints:
                                        nullable: false
            rollback:
                -   dropTable:
                        tableName: categories
